api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonapi: ["application/vnd.api+json"]
    error_formats:
        jsonapi: [ "application/vnd.api+json" ]
